config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#landing'
  
  resources :empresas
  resources :favorecidos
  resources :recibos
  resources :usuarios
  

  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    attr_accessor :updating_password

    after_initialize do
        self.updating_password ||= false
    end

    validates :nome, :presence => {:message => "Por favor, forneça o nome do usuário"}

    validates :email,
        :uniqueness => {:message => "Já existe um usuário com este e-mail"},
        :presence => {:message => "Por favor, forneça o nome completo do usuário"},
        :format => {:with => /\S+@\S+\.\S+/, :message => "O e-mail fornecido inválido"}

    validates :cpf,
        :presence => {:message => "O CPF do usuário deve ser fornecido"},
        :format => {:with => /([0-9]){3}\.([0-9]){3}\.([0-9]){3}-([0-9]){2}/, :message => "Deve seguir o formato: 000.000.000-00"}

    validates :password,
        :length => {:minimum => 6, :message => "Sua senha deve conter pelo menos 6 caracteres"},
        :format => {:with => /[a-zA-Z]+/, :message => "Sua senha deve conter letras e números"}, if: :should_update_password

    validates :password, :format => {:with => /[0-9]+/, :message => "Sua senha deve conter letras e números"}, if: :should_update_password

    # Fazer esta validação no controlador
    #trueValues = [true, "t", 1, "1", "true", "True", "Sim", "Yes", "S", "Y"]
    #validates :isAdmin, :exclusion => {:in => trueValues, :message => "Só pode ser atualizado por usuários administradores"}, :unless => :is_admin
    #validates :isBlocked, :exclusion => {:in => trueValues, :message => "Só pode ser atualizado por usuários administradores"}, :unless => :is_admin

    has_secure_password
    has_many :recibos, dependent: :destroy

    def to_s
        nome
    end

    def should_update_password
        new_record? or updating_password == "true"
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  before_action :is_admin, except: [:show, :edit, :update]
  before_action :me_or_admin, only: [:show, :edit, :update]

  # GET /usuarios
  # GET /usuarios.json
  def index
    if params.key? :usuario
      if params[:usuario].key? :nome
        @usuarios = Usuario.where("lower(nome) like '%#{params[:usuario][:nome].strip.downcase}%'").order(created_at: :desc).page(params[:page])
      elsif params[:usuario].key? :cpf
        @usuarios = Usuario.where("cpf like '%#{params[:usuario][:cpf].strip}%'").order(created_at: :desc).page(params[:page])
      elsif params[:usuario].key? :email
        @usuarios = Usuario.where("lower(email) like '%#{params[:usuario][:email].strip.downcase}%'").order(created_at: :desc).page(params[:page])
      end
    else
      @usuarios = Usuario.all.order(created_at: :desc).page(params[:page])
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @ultimos_recibos = @usuario.recibos.order(data: :desc)
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuarios_url, notice: 'Usuário criado com sucesso.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    @usuario.isAdmin = false unless current_user.isAdmin #bloqueio de atualização de permissão para usuarios que não são admin
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to (current_user.isAdmin ? usuarios_url : recibos_url), notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuário eliminado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :cpf, :email, :password, :password_confirmation, :isAdmin, :isBlocked, :updating_password)
    end

    def me_or_admin
      redirect_to :root, notice: "Acesso negado" unless current_user.isAdmin or current_user == @usuario
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= simple_form_for(@usuario) do |f| %>
  <div class="row">
    <div class="col">
      <%= f.error_notification %>
    </div>
  </div>

  <div class="form-inputs row">
    <div class="col">
      <%= f.input :nome %>
      <%= f.input :cpf, input_html: {class: "cpf_inputs"}, label: "CPF" %>
      <%= f.input :email, placeholder: "usuario@dominio.com.br", label: "E-mail" %>
      <%= f.input :isAdmin, as: :select, include_blank: false, label: "Usuário administrador?" if current_user.isAdmin %>
    </div>
    <div class="col">
      <%= f.input :updating_password, as: :select, label: "Deseja atualizar a senha?", include_blank: false unless @usuario.new_record? %>
      <%= f.input :password, label: "Senha" %>
      <%= f.input :password_confirmation, label: "Confirme sua senha", error: "Não é igual a senha" %>
      <%= f.input :isBlocked, as: :select, include_blank: false, label: "Usuário bloqueado?" if current_user.isAdmin %>
    </div>

    <div class="col-auto control-bttns">
      <%= button_tag type: 'submit', class: "btn btn-primary" do %>
        <i class="fas fa-save" aria-hidden="true"></i>
      <% end %> <br>
      <%= link_to fa_icon(:undo), (current_user.isAdmin ? usuarios_path : recibos_path), class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<div class="row">
  <div class="col">
    <h3>Edição de usuário</h3>
  </div>
</div>

<%= render 'form' %>

app/views/usuarios/index.html.erb
<div class="row">
  <div class="col">
      <h3>Lista de Usuários</h3>
  </div>
  <div class="col-4 d-flex justify-content-center">
    <%= paginate @usuarios %>
  </div>
</div>

<div class="modal fade" id="filter-form" tabindex="-1" role="dialog" aria-labelledby="filter-form-long-title" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Filtros</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for :usuario, url: usuarios_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :nome, label: false, placeholder: "Nome do usuario" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= simple_form_for :usuario, url: usuarios_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :cpf, label: false, placeholder: "CPF" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= simple_form_for :usuario, url: usuarios_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :email, label: false, placeholder: "E-mail" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= link_to "Remover Filtros", usuarios_path, class: "btn btn-danger btn-block"%>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col"><%= fa_icon("user", text:"Nome do usuário")%></th>
          <th scope="col"><%= fa_icon("at", text:"E-mail")%></th>
          <th scope="col" class="cpf-cnpj-col"><%= fa_icon("id-card", text:"CPF")%></th>
          <th scope="col"><%= fa_icon("user-secret", text:"Administrador?")%></th>
          <th scope="col"><%= fa_icon("lock", text:"Bloqueado?")%></th>
          <% if current_user.isAdmin %> <th scope="col"></th> <% end %>
          <th scope="col"><%= link_to fa_icon("filter"), "", class: "btn btn-primary control-bttn", "data-toggle" => "modal", "data-target" => "#filter-form" %></th>
          <th scope="col"><%= link_to fa_icon("plus-circle"), new_usuario_path, class: "btn btn-primary control-bttn" %></th>
        </tr>
      </thead>

      <tbody>
        <% @usuarios.each do |usuario| %>
          <tr scope="row">
            <td><%= usuario.nome %></td>
            <td><%= usuario.email %></td>
            <td class="cpf-cnpj-col"><%= usuario.cpf %></td>
            <td><%= usuario.isAdmin ? fa_icon(:check) + " Sim" : fa_icon(:times) + " Não" %></td>
            <td><%= usuario.isBlocked ? fa_icon(:check) + " Sim" : fa_icon(:times) + " Não" %></td>
            <td><%= link_to fa_icon("info-circle"), usuario, class: "btn btn-info control-bttn" %></td>
            <td><%= link_to fa_icon("pencil-alt"), edit_usuario_path(usuario), class: "btn btn-warning control-bttn" %></td>
            <% if current_user.isAdmin %>
              <td><%= link_to fa_icon(:trash), usuario, method: :delete, data: { confirm: 'Você tem certeza? Todos os recibos deste usuário serão apagados!' }, class: "btn btn-danger control-bttn" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/usuarios/new.html.erb
<div class="row">
    <div class="col">
        <h3>Criação de usuário</h3>
    </div>
</div>

<%= render 'form' %>

app/views/usuarios/show.html.erb
<div class="row">
  <div class="col">
    <h3>Detalhes do usuário</h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <p>
      <label><strong><%=fa_icon("user", text: "Nome:")%></strong></label>
      <%= @usuario.nome %>
    </p>
    <p>
      <label><strong><%=fa_icon("id-card", text: "CPF:")%></strong></label>
      <%= @usuario.cpf %>
    </p>
  </div>
  <div class="col">
    <p>
      <label><strong><%=fa_icon("at", text: "E-mail:")%></strong></label>
      <%= @usuario.email %>
    </p>

    <p>
      <label><strong><%=fa_icon("user-secret", text: "Administrador?")%></strong></label>
      <%= @usuario.isAdmin ? "Sim" : "Não" %>
    </p>

    <p>
      <label><strong><%=fa_icon("lock", text: "Bloqueado?")%></strong></label>
      <%= @usuario.isBlocked ? "Sim" : "Não" %>
    </p>
  </div>
  <div class="col-auto control-bttns">
    <%= link_to fa_icon(:list), (current_user.isAdmin ? usuarios_path : recibos_path), class: "btn btn-secondary" %> <br>
    <%= link_to fa_icon("pencil-alt"), edit_usuario_path(@usuario), class: "btn btn-warning" %> <br>
  </div>
</div>

<hr>

<% recibos = @ultimos_recibos.page(params[:page]).per(7) %>

<h5 class="text-center"><%= fa_icon("file-alt", text: "Últimos Recibos")%></h5>
<table class="table table-sm">
  <tr>
    <th scope="col"> <%= fa_icon("calendar-alt", text: "Data")%> </th>
    <th scope="col"> <%= fa_icon("money-bill-alt", text: "Valor")%> </th>
    <th scope="col"> <%= fa_icon("building", text: "Empresa")%> </th>
    <th scope="col"> <%= fa_icon("handshake", text: "Favorecido")%> </th>
    <th scope="col"> <%= fa_icon("comments", text: "Referente")%> </th>
    <th scope="col"></th>
  </tr>
  <% recibos.each do |r| %>
    <tr scope="row">
      <td> <%= localize r.data %> </td>
      <td> <%= number_to_currency r.valor %> </td>
      <td> <%= link_to r.empresa, r.empresa, class: "text-info" %> </td>
      <td> <%= link_to r.favorecido, r.favorecido, class: "text-info" %> </td>
      <td> <%= r.referente %> </td>
      <td> <%= link_to fa_icon("chevron-circle-right"), r, class: "btn btn-info control-bttn" %> </td>
    </tr>
  <% end %>
  <tr scope="row">
    <td colspan="6">
      <div class="row">
        <div class="col"> <%= page_entries_info recibos %> </div>
        <div class="col-auto mr-4"> <%= paginate recibos %> </div>
      </div>
    </td>
  </tr>
</table>