config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#landing'
  
  resources :empresas
  resources :favorecidos
  resources :recibos
  resources :usuarios
  

  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
    validates :nome, :presence => {:message => "O Nome da pessoa ou empresa deve ser fornecido"}

    validates :cpf_cnpj,
        :presence => {:message => "O CPF ou CNPJ da empresa deve ser fornecido"},
        :uniqueness => {:message => "CPF/CNPJ já cadastrado"},
        :format => {:with => /([0-9]{2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9]{2})|([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2})/,
                    :message => "Deve seguir o formato: 000.000.000-00 ou 00.000.000/0000-00"}


    has_many :recibos, dependent: :destroy

    attachment :info_img, content_type: ["image/jpeg", "image/png", "image/gif"]
    #validates :info_img, :presence => {:message => "Por favor forneça um selo com as informações da empresa"}

    def to_s
        nome
    end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  before_action :is_admin, except: [:show]

  # GET /empresas
  # GET /empresas.json
  def index
    if params.key? :empresa
      if params[:empresa].key? :nome
        @empresas = Empresa.where("lower(nome) like '%#{params[:empresa][:nome].strip.downcase}%'").order(created_at: :desc).page(params[:page])
      elsif params[:empresa].key? :cpf_cnpj
        @empresas = Empresa.where("cpf_cnpj like '%#{params[:empresa][:cpf_cnpj].strip}%'").order(created_at: :desc).page(params[:page])
      end
    else
      @empresas = Empresa.all.order(created_at: :desc).page(params[:page])
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    if current_user.isAdmin
      @ultimos_recibos = @empresa.recibos.order(data: :desc)
    else
      @ultimos_recibos = @empresa.recibos.where(usuario: current_user).order(data: :desc)
    end
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)
    respond_to do |format|
      if @empresa.save
        format.html { redirect_to empresas_url, notice: 'Empresa registrada com sucesso.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to empresas_url, notice: 'Empresa atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa elimida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nome, :cpf_cnpj, :info_img)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= simple_form_for(@empresa) do |f| %>
  <div class="row">
    <div class="col">
      <%= f.error_notification %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.input :nome %>
      <%= f.input :cpf_cnpj, label: "CPF/CNPJ", input_html: {class: "cpf_cnpj_inputs"} %>

      <div class="form-group string required empresa_info_img">
        <label class="control-label" for="empresa_info_img">
        <abbr title="required">*</abbr> Selo com informações da empresa </label>
        <%= f.attachment_field :info_img, class: "form-control" %>
        <span class="help-block"><%=f.error :info_img%></span>
      </div>
    </div>

    <div class="col-auto control-bttns">
      <%= button_tag type: 'submit', class: "btn btn-primary" do %>
        <i class="fas fa-save" aria-hidden="true"></i>
      <% end %> <br>
      <%= link_to fa_icon(:undo), empresas_path, class: "btn btn-secondary" %> <br>
    </div>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<div class="row">
  <div class="col">
    <h3>Editando Empresa</h3>
  </div>
</div>

<%= render 'form' %>

app/views/empresas/index.html.erb
<div class="row">
  <div class="col">
    <h3>Lista de Empresas</h3>
  </div>
  <div class="col-4 d-flex justify-content-center">
    <%= paginate @empresas %>
  </div>
</div>

<div class="modal fade" id="filter-form" tabindex="-1" role="dialog" aria-labelledby="filter-form-long-title" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Filtros</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for :empresa, url: empresas_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :nome, label: false, placeholder: "Nome da empresa" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= simple_form_for :empresa, url: empresas_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :cpf_cnpj, label: false, placeholder: "CPF/CNPJ" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= link_to "Remover Filtros", empresas_path, class: "btn btn-danger btn-block"%>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <table class="table table-hover table-no-bordered">
      <thead>
        <tr>
          <th scope="col"><%= fa_icon("building", text:"Nome da empresa")%></th>
          <th scope="col" class="cpf-cnpj-col"><%= fa_icon("id-card", text:"CPF/CNPJ")%></th>
          <th scope="col"><%= fa_icon("image", text:"Selo cadastrado")%></th>
          <th scope="col"></th>
          <th scope="col"> <%= link_to fa_icon(:filter), "", class: "btn btn-primary control-bttn", "data-toggle" => "modal", "data-target" => "#filter-form" %> </th>
          <th scope="col"> <%= link_to fa_icon("plus-circle"), new_empresa_path, class: "btn btn-primary control-bttn" %> </th>
        </tr>
      </thead>

      <tbody>
        <% @empresas.each do |empresa| %>
          <tr scope="row">
            <td><%= empresa.nome %></td>
            <td class="cpf-cnpj-col"><%= empresa.cpf_cnpj %></td>
            <td><%= empresa.info_img.blank? ? fa_icon(:times) + " Não" : fa_icon(:check) + " Sim" %></td>
            <td><%= link_to fa_icon("info-circle"), empresa, class: "btn btn-info control-bttn" %> </td>
            <td><%= link_to fa_icon("pencil-alt"), edit_empresa_path(empresa), class: "btn btn-warning control-bttn" %></td>
            <td><%= link_to fa_icon(:trash), empresa, method: :delete, data: { confirm: 'Você tem certeza? Todos os recibos desta empresa serão apagados!' }, class: "btn btn-danger control-bttn" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/empresas/new.html.erb
<div class="row">
  <div class="col">
    <h3>Nova Empresa</h3>
  </div>
</div>

<%= render 'form' %>

app/views/empresas/show.html.erb
<div class="row">
  <div class="col">
    <h3> Detalhes da empresa </h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <p>
      <label><strong><%=fa_icon("building", text: "Nome:")%></strong></label>
      <%= @empresa.nome %>
    </p>

    <p>
      <label><strong><%=fa_icon("id-card", text: "CPF/CNPJ:")%></strong></label>
      <%= @empresa.cpf_cnpj %>
    </p>
  </div>
  <div class="col">
    <% if @empresa.info_img.present? %>
      <label><strong><%=fa_icon("image", text: "Selo com informações da empresa:")%></strong></label> <br>
      <%= image_tag attachment_url(@empresa, :info_img), alt: "Imagem não encontrada" %>
    <% else %>
      <div class="alert alert-warning"><%=fa_icon("exclamation-circle", text: "Selo ainda não cadastrado")%></div>
    <% end %>
  </div>
  <div class="col-auto control-bttns">
    <%= link_to fa_icon(:list), empresas_path, class: "btn btn-secondary" %> <br>
    <%= link_to fa_icon("pencil-alt"), edit_empresa_path(@empresa), class: "btn btn-warning" %> <br>
  </div>
</div>

<hr>

<% recibos = @ultimos_recibos.page(params[:page]).per(7) %>

<h5 class="text-center"><%= fa_icon("file-alt", text: "Últimos Recibos")%></h5>
<table class="table table-sm">
  <tr>
    <th scope="col"> <%= fa_icon("calendar-alt", text: "Data")%> </th>
    <th scope="col"> <%= fa_icon("money-bill-alt", text: "Valor")%> </th>
    <th scope="col"> <%= fa_icon("handshake", text: "Favorecido")%> </th>
    <th scope="col"> <%= fa_icon("comments", text: "Referente")%> </th>
    <th scope="col"></th>
  </tr>
  <% recibos.each do |r| %>
    <tr scope="row">
      <td> <%= localize r.data %> </td>
      <td> <%= number_to_currency r.valor %> </td>
      <td> <%= link_to r.favorecido, r.favorecido, class: "text-info" %> </td>
      <td> <%= r.referente %> </td>
      <td> <%= link_to fa_icon("chevron-circle-right"), r, class: "btn btn-info control-bttn" %> </td>
    </tr>
  <% end %>
  <tr scope="row">
    <td colspan="5">
      <div class="row">
        <div class="col"> <%= page_entries_info recibos %> </div>
        <div class="col-auto mr-4"> <%= paginate recibos %> </div>
      </div>
    </td>
  </tr>
</table>