config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#landing'
  
  resources :empresas
  resources :favorecidos
  resources :recibos
  resources :usuarios
  

  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/recibo.rb
class Recibo < ActiveRecord::Base
    belongs_to :usuario
    belongs_to :favorecido
    belongs_to :empresa

    validates :data, :presence => {:message => "Informe a data deste recibo"}

    validates :valor,
        :presence => {:message => "Informe o valor em reais deste recibo"},
        :numericality => {:greater_than => 0, :message => "O valor do recibo deve ser positivo"}

    validates :valor_extenso, :presence => {:message => "Informe o valor por extenso deste recibo"}
    validates :referente, :presence => {:message => "Informe o que este recibo é referente"}

    validates :usuario, :presence => true
    validates :favorecido, :presence => {:message => "Favor informe o favorecido por este recibo"}
    validates :empresa, :presence => {:message => "Favor informe a empresa responsável por este recibo"}

    attachment :recibo_assinado, content_type: ["image/jpeg", "image/png", "image/gif", "application/pdf"]

    validate :validar_caracteres_para_pdf

    def to_s
        "Recibo Nº #{id}"
    end

    def validar_caracteres_para_pdf
        if valor_extenso.length + referente.length > 350
            errors.add(:referente, "Este texto está muito grande, não caberá no espaço do recibo")
        end
    end
end

app/controllers/recibos_controller.rb
class RecibosController < ApplicationController
  before_action :set_recibo, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  before_action :is_admin, only: [:destroy]
  before_action :mine_or_admin, except: [:destroy, :index, :new, :create]

  # GET /recibos
  # GET /recibos.json
  def index
    if current_user.isAdmin
      @recibos = Recibo.all
    else
      @recibos = current_user.recibos
    end

    if params.key? :recibo
      if params[:recibo].key? :id
        @recibos = @recibos.where("id = #{params[:recibo][:id].strip}")
      else
        if params[:recibo].key? :min_data and params[:recibo].key? :max_data
          params[:recibo][:min_data] = (Date.today - 30.years).to_s if params[:recibo][:min_data].blank?
          params[:recibo][:max_data] = (Date.today + 30.years).to_s if params[:recibo][:max_data].blank?
          @recibos = @recibos.where("data >= ? and data <=?", Date.parse(params[:recibo][:min_data]), Date.parse(params[:recibo][:max_data]))
        end

        if params[:recibo].key? :referente
          @recibos = @recibos.where("referente like '%#{params[:recibo][:referente].strip}%'")
        end

        if params[:recibo].key? :empresa
          @recibos = @recibos.joins(:empresa).where("empresas.nome like '%#{params[:recibo][:empresa].strip}%'")
        end

        if params[:recibo].key? :favorecido
          @recibos = @recibos.joins(:favorecido).where("favorecidos.nome like '%#{params[:recibo][:favorecido].strip}%'")
        end

        if params[:recibo].key? :usuario
          @recibos = @recibos.joins(:usuario).where("usuarios.nome like '%#{params[:recibo][:usuario].strip}%'")
        end
      end
    end
    @recibos = @recibos.includes(:empresa, :favorecido, :usuario).order(created_at: :desc).page(params[:page])
  end

  # GET /recibos/1
  # GET /recibos/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "recibo_#{@recibo.id}",   # Excluding ".pdf" extension.
               #disposition: "attachment",
               show_as_html: params.key?('debug'),
               #orientation: "Landscape",
               #page_size: "A4",
               encoding: 'utf-8',
               layout: 'recibo_layout',
               template: "recibos/show.pdf.erb",
               locals: {:recibo => @recibo, :empresa => @recibo.empresa}
      end
    end
  end

  # GET /recibos/new
  def new
    @recibo = Recibo.new(:data => Date.today)
  end

  # GET /recibos/1/edit
  def edit
  end

  # POST /recibos
  # POST /recibos.json
  def create
    @recibo = Recibo.new(recibo_params)
    @recibo.usuario = current_user
    respond_to do |format|
      if @recibo.save
        format.html { redirect_to recibos_url, notice: 'Recibo criado com sucesso' }
        format.json { render :show, status: :created, location: @recibo }
      else
        format.html { render :new }
        format.json { render json: @recibo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recibos/1
  # PATCH/PUT /recibos/1.json
  def update
    respond_to do |format|
      if @recibo.update(recibo_params)
        format.html { redirect_to recibos_url, notice: 'Recibo atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @recibo }
      else
        format.html { render :edit }
        format.json { render json: @recibo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recibos/1
  # DELETE /recibos/1.json
  def destroy
    @recibo.destroy
    respond_to do |format|
      format.html { redirect_to recibos_url, notice: 'Recibo eliminado com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recibo
      @recibo = Recibo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recibo_params
      params.require(:recibo).permit(:data, :valor, :valor_extenso, :referente, :recibo_assinado, :empresa_id, :favorecido_id, :max_date, :min_date)
    end

    def mine_or_admin
      redirect_to :root, notice: "Acesso negado" unless current_user.isAdmin or @recibo.usuario == current_user
    end
end

app/helpers/recibos_helper.rb
module RecibosHelper
end

app/views/recibos/_form.html.erb
<%= simple_form_for(@recibo) do |f| %>
  <% d = @recibo.recibo_assinado.nil? ? false : true %>
  <div class="row">
    <div class="col">
      <%= f.error_notification %>
    </div>
  </div>

  <div class="form-inputs">
    <div class="row">
      <div class="col">
        <%= f.input :data, disabled: d, label: "Data do recibo", input_html: {class: "date_inputs", value: localize(@recibo.data)}, as: :string %>
        <%= f.input :valor, disabled: d, label: "Valor do recibo (R$)", input_html: {class: "money_inputs"} %>
        <%= f.input :valor_extenso, disabled: d, label: "Valor por extenso" %>
      </div>

      <div class="col">
        <%= f.association :empresa, disabled: d %>
        <%= f.association :favorecido, disabled: d %>
        <%= f.input :referente, disabled: d, as: :text, label: "Recibo referente à" %>
      </div>

      <div class="col-auto control-bttns">
        <%= button_tag type: 'submit', class: "btn btn-primary" do %>
          <i class="fas fa-save" aria-hidden="true"></i>
        <% end %> <br>
        <%= link_to fa_icon(:undo), recibos_path, class: "btn btn-secondary" %> <br>
      </div>
    </div>

    <% unless @recibo.new_record? %>
      <div class="row">
        <div class="col">
          <div class="form-group string required empresa_info_img">
            <label class="control-label string required" for="empresa_info_img">
            <abbr title="required">*</abbr> Recibo assinado </label>
            <%= f.attachment_field :recibo_assinado, class: "form-control string required" %>
            <span class="help-block"><%=f.error :recibo_assinado%></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recibos/edit.html.erb
<div class="row">
  <div class="col">
    <h3>Edição de Recibo</h3>
  </div>
</div>

<%= render 'form' %>

app/views/recibos/index.html.erb
<div class="row">
  <div class="col">
    <h3>Lista de Recibos</h3>
  </div>
  <div class="col-4 d-flex justify-content-center">
    <%= paginate @recibos %>
  </div>
</div>

<div class="modal fade" id="filter-form" tabindex="-1" role="dialog" aria-labelledby="filter-form-long-title" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Filtros</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for :recibo, url: recibos_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :id, as: :integer, label: false, placeholder: "Número do recibo" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %> <hr>
        <%= simple_form_for :recibo, url: recibos_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :min_data, input_html: {"data-mask" => '99/99/9999'}, label: false, placeholder: "Data inicial" %>
              <%= f.input :max_data, input_html: {"data-mask" => '99/99/9999'}, :data => {:mask=> '99/99/9999'}, :data => {:mask=> '99/99/9999'}, label: false, placeholder: "Data final" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %> <hr>
        <%= simple_form_for :recibo, url: recibos_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :referente, as: :text,  label: false, placeholder: "Referente à" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %> <hr>
        <%= simple_form_for :recibo, url: recibos_path, method: :get do |f| %>
          <div class="row">
            <div class="col">
              <%= f.input :empresa, label: false, placeholder: "Nome da empresa" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= simple_form_for :recibo, url: recibos_path, method: :get do |f| %>
        <hr>
          <div class="row">
            <div class="col">
              <%= f.input :favorecido, label: false, placeholder: "Nome do favorecido" %>
            </div>
            <div class="col-auto">
              <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                <%= fa_icon(:search) %>
              <% end %>
            </div>
          </div>
        <% end %> <hr>
        <% if current_user.isAdmin %>
          <%= simple_form_for :recibo, url: recibos_path, method: :get do |f| %>
            <div class="row">
              <div class="col">
                <%= f.input :usuario, label: false, placeholder: "Nome do usuário" %>
              </div>
              <div class="col-auto">
                <%= button_tag type: :submit, class: "btn btn-primary control-bttn" do %>
                  <%= fa_icon(:search) %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        <%= link_to "Remover Filtros", recibos_path, class: "btn btn-danger btn-block"%>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col"><%=fa_icon("hashtag")%></th>
          <th scope="col"><%=fa_icon("calendar-alt", text:"Data")%></th>
          <th scope="col"><%=fa_icon("money-bill-alt", text:"Valor")%></th>
          <th scope="col"><%=fa_icon("comment", text:"Referente")%></th>
          <th scope="col"><%=fa_icon("building", text:"Empresa")%></th>
          <th scope="col"><%=fa_icon("handshake", text:"Favorecido")%></th>
          <% if current_user.isAdmin %> <th scope="col"><%=fa_icon("user", text:"Usuário")%></th> <% end %>
          <th scope="col" colspan="<%= current_user.isAdmin ? 2 : 1 %>"></th>
          <th scope="col"><%= link_to fa_icon("filter"), "", class: "btn btn-primary control-bttn", "data-toggle" => "modal", "data-target" => "#filter-form" %></th>
          <th scope="col"><%= link_to fa_icon("plus-circle"), new_recibo_path, class: "btn btn-primary control-bttn" %></th>
        </tr>
      </thead>

      <tbody>
        <% @recibos.each do |recibo| %>
          <tr scope="row">
            <td><%= recibo.id %></td>
            <td><%= localize recibo.data %></td>
            <td><%= number_to_currency recibo.valor %></td>
            <td><%= recibo.referente %></td>
            <td><%= recibo.empresa.nome %></td>
            <td><%= recibo.favorecido.nome %></td>
            <% if current_user.isAdmin %> <td><%= recibo.usuario.nome %></td> <% end %>
            <td><%= link_to fa_icon("info-circle"), recibo, class: "btn btn-info control-bttn" %></td>
            <td><%= link_to fa_icon(:print), recibo_path(recibo, :format => :pdf), class: "btn btn-info control-bttn" %></td>
            <td><%= link_to fa_icon("pencil-alt"), edit_recibo_path(recibo), class: "btn btn-warning control-bttn" %></td>
            <% if current_user.isAdmin %> <td class="col-auto"><%= link_to fa_icon(:trash), recibo, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger control-bttn" %></td> <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/recibos/new.html.erb
<div class="row">
  <div class="col">
    <h3>Novo Recibo</h3>
  </div>
</div>

<%= render 'form' %>

app/views/recibos/show.html.erb
<div class="row">
  <div class="col">
    <h3> <%= @recibo %> </h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <p>
      <label><%=fa_icon("calendar-alt", text: "Data:")%></label>
      <%= localize @recibo.data %>
    </p>

    <p>
      <label><%=fa_icon("money-bill-alt", text: "Valor do recibo:")%></label>
      <%= number_to_currency @recibo.valor %>
    </p>

    <p>
      <label><%=fa_icon("money-bill-alt", text: "Valor por extenso:")%></label>
      <%= @recibo.valor_extenso %>
    </p>

    <p>
      <label><%=fa_icon("comments", text: "Referente à:")%></label>
      <%= @recibo.referente %>
    </p>
  </div>
  <div class="col">
    <p>
      <label><strong><%=fa_icon("building", text: "Empresa:")%></strong></label>
      <%= link_to @recibo.empresa.nome, @recibo.empresa, class: "text-info" %>
    </p>

    <p>
      <label><strong><%=fa_icon("handshake", text: "Favorecido:")%></strong></label>
      <%= link_to @recibo.favorecido.nome, @recibo.favorecido, class: "text-info" %>
    </p>

    <% if current_user.isAdmin %>
      <p>
        <label><strong><%=fa_icon("user", text: "Usuário responsável:")%></strong></label>
        <%= link_to @recibo.usuario.nome, @recibo.usuario, class: "text-info" %>
      </p>
    <% end %>

    <p>
      <% if @recibo.recibo_assinado.nil? %>
        <div class="alert alert-warning"> <%=fa_icon("exclamation-circle", text: "O Recibo assinado ainda não foi salvo")%></div>
      <% else %>
        <%= link_to fa_icon("external-link", text: "Download do recibo assinado", right: true), attachment_url(@recibo, :recibo_assinado), class: "btn btn-sm btn-info" %>
      <% end %>
    </p>
  </div>
  <div class="col-auto control-bttns">
    <%= link_to fa_icon(:list), recibos_path, class: "btn btn-secondary" %> <br>
    <%= link_to fa_icon("pencil-alt"), edit_recibo_path(@recibo), class: "btn btn-warning" %> <br>
    <%= link_to fa_icon(:print), recibo_path(@recibo, :format => :pdf), class: "btn btn-info" %> <br>
  </div>
</div>

app/views/recibos/show.pdf.erb
<% 2.times do |i| %>
  <% if i == 1 %>
    <hr class="linha_entre_vias">
  <% end %>

  <div class="via">

    <div class="num-via"> <%=i+1%>º Via </div>

    <div class="logo-div">
      <% logo_tag = empresa.info_img.blank? ? "" : wicked_pdf_image_tag(attachment_url(empresa, :info_img), width: "100%", height: "100%") %>
      <%# logo_tag = empresa.info_img.nil? ? "" : wicked_pdf_image_tag("http://www.betaetiquetas.com.br/product_images/y/643/teste1__63139_zoom.png", width: "100%", height: "100%", alt: "Selo da empresa não encontrado, faça upload novamente") %>
      <%# logo_tag = wicked_pdf_image_tag("ImagemReciboCasebras.png", width: "100%", height: "100%", alt: "") %>
      <% logger.debug "DEBUG " + logo_tag %> <%= logo_tag %>
    </div>


    <div class="recibo-titulo">
      <%=recibo%>
    </div>

    <div class="recibo-valor">
      <%= number_to_currency recibo.valor %>
    </div>

    <div class="recibo-texto">
      Recebi(emos) de <%=recibo.empresa.nome%> a importância de <%=recibo.valor_extenso%> referente à <%=recibo.referente%>
    </div>

    <div class="recibo-assinatura">
      <div class="data"><%=localize recibo.data, format: :long%></div>
      <hr>
      <div class="favorecido"> <%=recibo.favorecido.nome%>
      <br>
      <span class="cpf_cnpj"><strong>CPF/CNPJ</strong> <%= recibo.favorecido.cpf_cnpj %></span>
      <% unless recibo.favorecido.rg.nil? %>
        | <span class="rg"><strong>RG</strong> <%= recibo.favorecido.rg %></span
      <% end %>
      </div>
      </div>
    </div>

  </div> <!--via-->
<% end %>