config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#landing'
  
  resources :empresas
  resources :favorecidos
  resources :recibos
  resources :usuarios
  

  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recibos Casebrás</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% if session[:user_id] %>
    <nav class="navbar navbar-toggleable-md navbar-expand-xl navbar-light bg-light mb-4 rounded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <span class="navbar-brand">
        <%= image_tag "logo_casebras.png", :alt => "Login Casebrás", style: "height: 35px;" %>
        Recibos Casebrás
      </span>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if current_user.isAdmin %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to fa_icon("file-alt", text: "Recibos"), recibos_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to fa_icon("building", text: "Empresas"), empresas_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to fa_icon("handshake", text: "Favorecidos"), favorecidos_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to fa_icon("users", text: "Usuários"), usuarios_path, class: "nav-link" %>
            </li>
          </ul>
        <% end %>
        <ul class="navbar-nav  ml-auto">
          <li class="nav-item">
            <%= link_to fa_icon("user", text: current_user.nome.split.first), usuario_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to fa_icon("sign-out-alt", text: "Sair"), logout_path, class: "btn btn-danger" %>
          </li>
        </ul>
      </div>
    </nav>
  <% end %>

  <div class="content" style="min-height: 600px">
    <% unless notice.nil? %>
      <div class="alert alert-info alert-dismissible fade show w-50 mx-auto text-center" role="alert" style="min-width: 20em">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <p id="notice"><%= notice %></p>
      </div>
    <% end %>

    <%= yield %>
  </div>

<footer class="footer text-right m-3 bg-faded"> <hr>
  <span class="text-muted"> Recibos Casebrás | contato: helpdesk@casebrás.com.br </span>
</footer>

</div>

<script defer src="<%=asset_path :fontawesome%>"></script>

</body>
</html>

app/views/layouts/recibo_layout.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recibo Nº<%=recibo.id%></title>
  <style>
    .via {
      width: 15cm;
      height: 11cm;
      border-style: solid;
      border-width: 2px;
      margin: .8cm auto;
      padding: 0.5cm;
      position: relative;
    }

    .num-via {
      float: left;
      width: 10em;
      display: inline;
    }

    .logo-div {
      width: 10cm;
      height: 1.8cm;
      max-width: 10cm;
      max-height: 1.8cm;
      float: right;
      border-style: solid;
      border-width: 0px;
      display:inline;
    }

    .recibo-titulo, .recibo-valor {
      font-size: 14pt;
      font-weight: bold;
    }

    .recibo-titulo {
      position: absolute;
      top: 2.7cm;
    }

    .recibo-valor {
      position: absolute;
      top: 2.7cm;
      right: 3cm;
    }

    .recibo-texto, .recibo-assinatura {
      font-size: 12pt;
    }

    .recibo-texto {
      position: absolute;
      top: 4.5cm;
      text-align: justify;
      padding-right: inherit;
    }

    .recibo-assinatura {
      position: absolute;
      top: 8.3cm;
      width: 100%;
      padding-right: inherit;
    }

    .recibo-assinatura .favorecido,
    .recibo-assinatura .data{
      text-align: center;
    }

    .recibo-assinatura hr {
      width: 8cm;
      margin-top: 1.5cm;
    }

    .recibo-assinatura .favorecido .cpf_cnpj,
    .recibo-assinatura .favorecido .rg {
      font-size: 10pt;
    }

    /*.recibo-assinatura .favorecido .cpf_cnpj {*/
    /*  float: left;*/
    /*}*/

    /*.recibo-assinatura .favorecido .rg {*/
    /*  float: right;*/
    /*}*/

    hr.linha_entre_vias {
      border-top: 1px dashed #000;
    }

  </style>

  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.slim.min.js"> </script>
</head>
<body>

<%= yield %>

</body>
</html>